nodeVersion: "24.18.0"
saveExact: true
linkWorkspacePackages: true
nodeLinker: hoisted # Needed for Theia's version check
packages:
  - theia-extensions/*
  - browser-app
  - electron-app
  - tests
allowBuilds:
  "@parcel/watcher": true
  "@theia/ffmpeg": true
  "@vscode/windows-ca-certs": true
  "@yukibana/cli@https://codeload.github.com/tothambrus11/yukibana-cloud/tar.gz/a84256361b71c61d0df3f25232ed27c9eb4f62b1#path:/cli": true
  chromedriver: true
  core-js: true
  drivelist: true
  electron-chromedriver: true
  electron-winstaller: true
  esbuild: true
  keytar: true
  msgpackr-extract: true
  native-keymap: true
  node-pty: true
  nx: true
  puppeteer: true
