# Adapted from https://github.com/eclipse-theia/theia-ide/blob/74bd976ef60102bdbaf754817c88d00811465e72/.github/workflows/build.yml
name: Build, package and test
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - '**/*.typ'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - '**/*.typ'

jobs:
  build:
    name: ${{ matrix.os }}, Node.js v${{ matrix.node }}

    strategy:
      fail-fast: false
      matrix:
        os: [windows-2022, ubuntu-22.04, macos-15, macos-15-intel]
        node: ["24.x"]

    runs-on: ${{ matrix.os }}
    timeout-minutes: 60

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node }}
          registry-url: "https://registry.npmjs.org"

      - name: Use Python 3.13
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      - name: Install dependencies
        shell: bash
        run: yarn --skip-integrity-check --network-timeout 100000
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Lint
        shell: bash
        run: yarn lint
        env:
          NODE_OPTIONS: --max_old_space_size=4096

      - name: Build dev package (Windows, Linux)
        if: (runner.os == 'Windows' || runner.os == 'Linux') && github.event_name == 'pull_request'
        shell: bash
        run: |
          yarn build:dev
          yarn download:plugins
          yarn package:applications:preview
        env:
          NODE_OPTIONS: --max_old_space_size=4096
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build prod package (Windows, Linux)
        if: (runner.os == 'Windows' || runner.os == 'Linux') && github.event_name != 'pull_request'
        shell: bash
        run: |
          yarn build
          yarn download:plugins
          yarn package:applications
        env:
          NODE_OPTIONS: --max_old_space_size=4096
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update electron-builder.yml for macos-15
        if: matrix.os == 'macos-15'
        run: |
          sed -i '' 's|https://download.eclipse.org/theia/ide/latest/macos|https://download.eclipse.org/theia/ide/latest/macos-arm|g' electron-app/electron-builder.yml

      - name: Build prod package (Mac)
        if: runner.os == 'macOS'
        shell: bash
        run: |
          yarn build
          yarn download:plugins
          yarn package:applications
        env:
          NODE_OPTIONS: --max_old_space_size=4096
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Mac Dist Files
        if: runner.os == 'macOS'
        uses: actions/upload-artifact@v6
        with:
          name: ${{ matrix.os == 'macos-15-intel' && 'mac-x64' || matrix.os == 'macos-15' && 'mac-arm64'}}
          path: |
            electron-app/dist/**
            !electron-app/dist/mac/**
            !electron-app/dist/mac-arm64/**
          retention-days: 1

      - name: Upload Windows Dist Files
        if: runner.os == 'Windows' && github.event_name != 'pull_request'
        uses: actions/upload-artifact@v6
        with:
          name: windows
          path: |
            electron-app/dist/**
          retention-days: 1

      - name: Upload Linux Dist Files
        if: runner.os == 'Linux' && github.event_name != 'pull_request'
        uses: actions/upload-artifact@v6
        with:
          name: linux
          path: |
            electron-app/dist/**
          retention-days: 1

      - name: Test (Linux)
        if: runner.os == 'Linux'
        run: |
          xvfb-run -a yarn tests ui-tests-ci-electron

      - name: Test (Windows)
        if: runner.os == 'Windows'
        shell: bash
        run: |
          yarn tests ui-tests-ci-electron

      - name: Test (macOS)
        if: runner.os == 'macOS'
        shell: bash
        run: |
          yarn tests ui-tests-ci-electron

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v6
        with:
          name: test-results-${{ matrix.os }}
          path: test-results/
          if-no-files-found: ignore
          retention-days: 5
